import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@descope/nextjs-sdk";

const interFont = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const poppinsFont = Poppins({
  weight: "500",
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const projectId = process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID || "";
  const cookieOptions = {
    sameSite: "Lax" as const,
    secure: process.env.NODE_ENV !== "development",
  }
  return (
    <AuthProvider
      projectId={projectId}
      refreshTokenViaCookie={cookieOptions}
      sessionTokenViaCookie={cookieOptions}
    >
      <html
        lang="en"
        className={`${interFont.variable} ${poppinsFont.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </AuthProvider>
  );
}
